[package]
name = "vi-cli-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
openidconnect = { features = ["reqwest-blocking"], version = "4.0.0" }
reqwest = { features = ["blocking"], version = "0.12.12" }
serde = { features = ["derive"], version = "1.0.218" }
serde_json = "1.0.140"
serde_qs = "0.13.0"
url = { features = ["serde"], version = "2.5.4" }
